### ISSUE TITLE
Does this extension still work?

### ISSUE THREAD

**Issue by BrentH-Alnico** [ShawnLin013/vscode-file-name-search#6]
Extension does not work...
With file selected, I click Search File Name...it opens the search panel but does not insert the filename into the search field.

UPDATE:
However, it does copy the filename to the clipboard, so I can click paste and it works.
But, it will re-search whatever is currently in the search box, since it is not replacing it until I click paste.

Running on Win10, vscode 1.44

**Comment by jacques-hoventer** [comment]
Same issue here!

**Comment by ShawnLin013** [comment]
@alnico2001 @jacques-hoventer
Sorry for the late update. Please upgrade the extension to v0.0.5. It should be working correctly again.

**Comment by jacques-hoventer** [comment]
Seems to be working again. Thanks!
