### ISSUE TITLE
Don't work on mac

### ISSUE THREAD

**Issue by zszen** [ShawnLin013/vscode-file-name-search#7]
Right click menu and search, the search bar don't show the file name.

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (2 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by ShawnLin013** [comment]
@zszen 
Sorry for the late update. Please upgrade the extension to v0.0.5. It should be working correctly again.
